package supervisor

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"strings"
)

// BailAssessment is the structured output an agent produces when it bails.
type BailAssessment struct {
	Reason        string   `json:"reason"`
	FilesExamined []string `json:"files_examined"`
	Plan          string   `json:"plan"`
	SubIssues     []string `json:"sub_issues,omitempty"`
	Complexity    string   `json:"complexity"`
}

// extractBailReport parses a <bail-report> JSON block from the agent's result text.
// Returns nil if no report found.
func extractBailReport(resultText string) *BailAssessment {
	const openTag = "<bail-report>"
	const closeTag = "</bail-report>"

	start := strings.LastIndex(resultText, openTag)
	if start < 0 {
		return nil
	}
	start += len(openTag)

	end := strings.LastIndex(resultText, closeTag)
	if end < 0 || end <= start {
		return nil
	}

	jsonStr := strings.TrimSpace(resultText[start:end])
	var report BailAssessment
	if err := json.Unmarshal([]byte(jsonStr), &report); err != nil {
		debugLog("bail report parse failed", "error", err.Error())
		return nil
	}

	return &report
}

// extractBailReportFromLog reads the agent log file and searches for a <bail-report> block.
// The agent may embed the report in a tool call (e.g., gh issue comment) rather than in its
// final result text. We read the whole log as a string and search for the tags.
func extractBailReportFromLog(logPath string) *BailAssessment {
	if logPath == "" {
		return nil
	}
	data, err := os.ReadFile(logPath)
	if err != nil {
		return nil
	}
	// Limit to last 50KB to avoid scanning huge logs.
	content := string(data)
	if len(content) > 50000 {
		content = content[len(content)-50000:]
	}
	return extractBailReport(content)
}

// formatBailComment renders a bail report as a markdown issue comment.
func formatBailComment(report *BailAssessment) string {
	var b strings.Builder
	b.WriteString("## Agent Bail Report\n\n")
	fmt.Fprintf(&b, "**Reason:** %s\n\n", report.Reason)
	fmt.Fprintf(&b, "**Complexity:** %s\n\n", report.Complexity)

	if len(report.FilesExamined) > 0 {
		b.WriteString("### Files Examined\n")
		for _, f := range report.FilesExamined {
			fmt.Fprintf(&b, "- `%s`\n", f)
		}
		b.WriteString("\n")
	}

	if report.Plan != "" {
		b.WriteString("### Implementation Plan\n")
		b.WriteString(report.Plan)
		b.WriteString("\n\n")
	}

	if len(report.SubIssues) > 0 {
		b.WriteString("### Suggested Decomposition\n")
		for _, s := range report.SubIssues {
			fmt.Fprintf(&b, "- %s\n", s)
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n*Generated by minder agent*")
	return b.String()
}

// handleBailReport extracts, stores, and posts a bail report.
// It checks the result text first, then falls back to scanning the raw log file
// (the agent may have embedded the bail-report in a tool call like gh issue comment).
func (m *DefaultJobManager) handleBailReport(ctx context.Context, resultText string) {
	sc := m.sc
	job := sc.Job

	report := extractBailReport(resultText)
	if report == nil {
		// Fallback: scan the raw log file for bail-report tags.
		report = extractBailReportFromLog(sc.LogPath)
	}
	if report == nil {
		return
	}

	// Store in result_json.
	data, err := json.Marshal(report)
	if err != nil {
		return
	}
	_ = sc.Store.UpdateJobResult(job.ID, string(data))

	// Update failure with structured reason.
	_ = sc.Store.UpdateJobFailure(job.ID, "bailed", report.Reason)

	// Note: we don't post a comment here because the agent is instructed to post
	// its own bail comment on the issue. We only extract and store the structured data.

	sc.EmitEvent("info", fmt.Sprintf("Bail report captured for %s: %s", sc.JobLabel(), report.Reason))

	debugLog("bail report extracted",
		"label", sc.JobLabel(),
		"complexity", report.Complexity,
		"files", len(report.FilesExamined),
		"sub_issues", len(report.SubIssues),
	)
}
