package supervisor

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	runtimepkg "github.com/aptx-health/agent-minder/internal/runtime"
)

// BailAssessment is the structured output an agent produces when it bails.
type BailAssessment struct {
	Reason        string   `json:"reason"`
	FilesExamined []string `json:"files_examined"`
	Plan          string   `json:"plan"`
	SubIssues     []string `json:"sub_issues,omitempty"`
	Complexity    string   `json:"complexity"`
}

// formatBailComment renders a bail report as a markdown issue comment.
func formatBailComment(report *BailAssessment) string {
	var b strings.Builder
	b.WriteString("## Agent Bail Report\n\n")
	fmt.Fprintf(&b, "**Reason:** %s\n\n", report.Reason)
	fmt.Fprintf(&b, "**Complexity:** %s\n\n", report.Complexity)

	if len(report.FilesExamined) > 0 {
		b.WriteString("### Files Examined\n")
		for _, f := range report.FilesExamined {
			fmt.Fprintf(&b, "- `%s`\n", f)
		}
		b.WriteString("\n")
	}

	if report.Plan != "" {
		b.WriteString("### Implementation Plan\n")
		b.WriteString(report.Plan)
		b.WriteString("\n\n")
	}

	if len(report.SubIssues) > 0 {
		b.WriteString("### Suggested Decomposition\n")
		for _, s := range report.SubIssues {
			fmt.Fprintf(&b, "- %s\n", s)
		}
		b.WriteString("\n")
	}

	b.WriteString("---\n*Generated by minder agent*")
	return b.String()
}

// handleBailReport stores a bail report on the job and emits an event. The
// runtime owns extraction (substring scan, JSON-escape unwinding); the
// supervisor only decodes the raw block into its richer BailAssessment shape
// for storage and downstream rendering.
func (m *DefaultJobManager) handleBailReport(ctx context.Context, report *runtimepkg.BailReport) {
	if report == nil {
		return
	}
	sc := m.sc
	job := sc.Job

	var assessment BailAssessment
	if len(report.Native) > 0 {
		_ = json.Unmarshal(report.Native, &assessment)
	}
	if assessment.Reason == "" {
		assessment.Reason = report.Reason
	}
	if assessment.Plan == "" {
		assessment.Plan = report.Detail
	}

	data, err := json.Marshal(&assessment)
	if err != nil {
		return
	}
	_ = sc.Store.UpdateJobResult(job.ID, string(data))
	_ = sc.Store.UpdateJobFailure(job.ID, "bailed", assessment.Reason)

	sc.EmitEvent("info", fmt.Sprintf("Bail report captured for %s: %s", sc.JobLabel(), assessment.Reason))

	debugLog("bail report extracted",
		"label", sc.JobLabel(),
		"complexity", assessment.Complexity,
		"files", len(assessment.FilesExamined),
		"sub_issues", len(assessment.SubIssues),
	)
}
