package supervisor

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestExtractBailReport_Valid(t *testing.T) {
	input := `I explored the codebase but this is too complex.

<bail-report>
{
  "reason": "Issue requires design decisions not specified",
  "files_examined": ["internal/auth/handler.go", "internal/auth/middleware.go", "pkg/token/jwt.go"],
  "plan": "1. Define the new auth flow\n2. Update middleware\n3. Add tests",
  "sub_issues": ["Refactor middleware to support multiple providers", "Add JWT validation tests"],
  "complexity": "large"
}
</bail-report>`

	report := extractBailReport(input)
	if report == nil {
		t.Fatal("expected bail report, got nil")
	}
	if report.Reason != "Issue requires design decisions not specified" {
		t.Errorf("reason = %q", report.Reason)
	}
	if len(report.FilesExamined) != 3 {
		t.Errorf("files_examined count = %d, want 3", len(report.FilesExamined))
	}
	if report.Complexity != "large" {
		t.Errorf("complexity = %q, want large", report.Complexity)
	}
	if len(report.SubIssues) != 2 {
		t.Errorf("sub_issues count = %d, want 2", len(report.SubIssues))
	}
}

func TestExtractBailReport_NoTags(t *testing.T) {
	input := "I couldn't complete this task because it was too hard."
	report := extractBailReport(input)
	if report != nil {
		t.Error("expected nil for input without bail-report tags")
	}
}

func TestExtractBailReport_InvalidJSON(t *testing.T) {
	input := `<bail-report>
not valid json
</bail-report>`
	report := extractBailReport(input)
	if report != nil {
		t.Error("expected nil for invalid JSON")
	}
}

func TestExtractBailReport_EmptyFields(t *testing.T) {
	input := `<bail-report>
{
  "reason": "stuck",
  "files_examined": [],
  "plan": "",
  "complexity": "small"
}
</bail-report>`

	report := extractBailReport(input)
	if report == nil {
		t.Fatal("expected bail report")
	}
	if report.Reason != "stuck" {
		t.Errorf("reason = %q", report.Reason)
	}
	if len(report.FilesExamined) != 0 {
		t.Errorf("files_examined should be empty")
	}
	if len(report.SubIssues) != 0 {
		t.Errorf("sub_issues should be empty")
	}
}

func TestExtractBailReport_MultipleBlocks(t *testing.T) {
	// If the agent outputs multiple bail-report blocks (unlikely but possible),
	// we take the last one (LastIndex behavior).
	input := `<bail-report>
{"reason": "first attempt", "files_examined": [], "plan": "", "complexity": "small"}
</bail-report>

Actually let me try again...

<bail-report>
{"reason": "second attempt", "files_examined": ["main.go"], "plan": "do the thing", "complexity": "medium"}
</bail-report>`

	report := extractBailReport(input)
	if report == nil {
		t.Fatal("expected bail report")
	}
	if report.Reason != "second attempt" {
		t.Errorf("reason = %q, want 'second attempt' (should use last block)", report.Reason)
	}
}

func TestFormatBailComment(t *testing.T) {
	report := &BailAssessment{
		Reason:        "Needs design decisions",
		FilesExamined: []string{"auth.go", "middleware.go"},
		Plan:          "1. Define flow\n2. Implement",
		SubIssues:     []string{"Sub-issue A", "Sub-issue B"},
		Complexity:    "large",
	}

	comment := formatBailComment(report)

	checks := []struct {
		name    string
		substr  string
		present bool
	}{
		{"header", "## Agent Bail Report", true},
		{"reason", "**Reason:** Needs design decisions", true},
		{"complexity", "**Complexity:** large", true},
		{"files header", "### Files Examined", true},
		{"file entry", "`auth.go`", true},
		{"plan header", "### Implementation Plan", true},
		{"plan content", "1. Define flow", true},
		{"decomp header", "### Suggested Decomposition", true},
		{"sub-issue", "Sub-issue A", true},
		{"footer", "Generated by minder agent", true},
	}

	for _, c := range checks {
		found := strings.Contains(comment, c.substr)
		if found != c.present {
			t.Errorf("%s: contains(%q) = %v, want %v", c.name, c.substr, found, c.present)
		}
	}
}

func TestFormatBailComment_Minimal(t *testing.T) {
	report := &BailAssessment{
		Reason:     "stuck",
		Complexity: "small",
	}

	comment := formatBailComment(report)

	if strings.Contains(comment, "### Files Examined") {
		t.Error("should not have files section when empty")
	}
	if strings.Contains(comment, "### Implementation Plan") {
		t.Error("should not have plan section when empty")
	}
	if strings.Contains(comment, "### Suggested Decomposition") {
		t.Error("should not have decomposition section when empty")
	}
}

func TestBailAssessment_JSONRoundTrip(t *testing.T) {
	report := &BailAssessment{
		Reason:        "too complex",
		FilesExamined: []string{"a.go", "b.go"},
		Plan:          "step 1, step 2",
		SubIssues:     []string{"sub1"},
		Complexity:    "medium",
	}

	data, err := json.Marshal(report)
	if err != nil {
		t.Fatal(err)
	}

	var decoded BailAssessment
	if err := json.Unmarshal(data, &decoded); err != nil {
		t.Fatal(err)
	}

	if decoded.Reason != report.Reason {
		t.Errorf("reason mismatch: %q vs %q", decoded.Reason, report.Reason)
	}
	if decoded.Complexity != report.Complexity {
		t.Errorf("complexity mismatch")
	}
	if len(decoded.FilesExamined) != 2 {
		t.Errorf("files count mismatch")
	}
}

func TestExtractBailReportFromLog(t *testing.T) {
	// Simulate a log file where the bail-report appears in agent text output.
	logContent := `{"type":"assistant","message":{"content":[{"type":"text","text":"I need to bail on this task."}]}}
some other log line
<bail-report>
{"reason":"too complex","files_examined":["a.go"],"plan":"step 1","complexity":"large"}
</bail-report>
{"type":"result","subtype":"","is_error":false,"result":"Done, I bailed."}`

	dir := t.TempDir()
	logPath := filepath.Join(dir, "test.log")
	if err := os.WriteFile(logPath, []byte(logContent), 0644); err != nil {
		t.Fatal(err)
	}

	report := extractBailReportFromLog(logPath)
	if report == nil {
		t.Fatal("expected bail report from log fallback")
	}
	if report.Reason != "too complex" {
		t.Errorf("reason = %q", report.Reason)
	}
	if report.Complexity != "large" {
		t.Errorf("complexity = %q", report.Complexity)
	}
}

func TestExtractBailReportFromLog_NoReport(t *testing.T) {
	dir := t.TempDir()
	logPath := filepath.Join(dir, "test.log")
	if err := os.WriteFile(logPath, []byte(`{"type":"result","result":"all done"}`), 0644); err != nil {
		t.Fatal(err)
	}

	report := extractBailReportFromLog(logPath)
	if report != nil {
		t.Error("expected nil when no bail-report in log")
	}
}

func TestExtractBailReportFromLog_MissingFile(t *testing.T) {
	report := extractBailReportFromLog("/nonexistent/path.log")
	if report != nil {
		t.Error("expected nil for missing file")
	}
}

func TestExtractBailReportFromLog_EmptyPath(t *testing.T) {
	report := extractBailReportFromLog("")
	if report != nil {
		t.Error("expected nil for empty path")
	}
}
