package supervisor

import (
	"encoding/json"
	"strings"
	"testing"
)

func TestFormatBailComment(t *testing.T) {
	report := &BailAssessment{
		Reason:        "Needs design decisions",
		FilesExamined: []string{"auth.go", "middleware.go"},
		Plan:          "1. Define flow\n2. Implement",
		SubIssues:     []string{"Sub-issue A", "Sub-issue B"},
		Complexity:    "large",
	}

	comment := formatBailComment(report)

	checks := []struct {
		name    string
		substr  string
		present bool
	}{
		{"header", "## Agent Bail Report", true},
		{"reason", "**Reason:** Needs design decisions", true},
		{"complexity", "**Complexity:** large", true},
		{"files header", "### Files Examined", true},
		{"file entry", "`auth.go`", true},
		{"plan header", "### Implementation Plan", true},
		{"plan content", "1. Define flow", true},
		{"decomp header", "### Suggested Decomposition", true},
		{"sub-issue", "Sub-issue A", true},
		{"footer", "Generated by minder agent", true},
	}

	for _, c := range checks {
		found := strings.Contains(comment, c.substr)
		if found != c.present {
			t.Errorf("%s: contains(%q) = %v, want %v", c.name, c.substr, found, c.present)
		}
	}
}

func TestFormatBailComment_Minimal(t *testing.T) {
	report := &BailAssessment{
		Reason:     "stuck",
		Complexity: "small",
	}

	comment := formatBailComment(report)

	if strings.Contains(comment, "### Files Examined") {
		t.Error("should not have files section when empty")
	}
	if strings.Contains(comment, "### Implementation Plan") {
		t.Error("should not have plan section when empty")
	}
	if strings.Contains(comment, "### Suggested Decomposition") {
		t.Error("should not have decomposition section when empty")
	}
}

func TestBailAssessment_JSONRoundTrip(t *testing.T) {
	report := &BailAssessment{
		Reason:        "too complex",
		FilesExamined: []string{"a.go", "b.go"},
		Plan:          "step 1, step 2",
		SubIssues:     []string{"sub1"},
		Complexity:    "medium",
	}

	data, err := json.Marshal(report)
	if err != nil {
		t.Fatal(err)
	}

	var decoded BailAssessment
	if err := json.Unmarshal(data, &decoded); err != nil {
		t.Fatal(err)
	}

	if decoded.Reason != report.Reason {
		t.Errorf("reason mismatch: %q vs %q", decoded.Reason, report.Reason)
	}
	if decoded.Complexity != report.Complexity {
		t.Errorf("complexity mismatch")
	}
	if len(decoded.FilesExamined) != 2 {
		t.Errorf("files count mismatch")
	}
}
